const modules=[
{id:'attention',name:'Attention & Concentration',icon:'◎',time:5,qs:[
['Which symbol is different?','◆ ◆ ◆ ◇ ◆',['A','B','C','D'],2],['Select the number 7','3  7  9  2  5',['3','7','9','2'],1],['Which pair matches exactly?','AB7Q9',['AB7Q9','AB7O9','A87Q9','AB7Q8'],0],['How many triangles are shown?','▲ ▲ ● ▲ ●',['1','2','3','4'],2]]},
{id:'reasoning',name:'Logical Reasoning',icon:'◆',time:6,qs:[
['What comes next?','2  4  8  16  ?',['18','24','32','36'],2],['What comes next?','5  8  11  14  ?',['16','17','18','19'],1],['If all trains are vehicles and some vehicles are electric, which is certain?','',['All trains are electric','Some trains may be electric','No trains are electric','All electric things are trains'],1],['Find the odd one out.','12  18  24  31  36',['12','18','31','36'],2]]},
{id:'numerical',name:'Numerical Ability',icon:'＋',time:6,qs:[
['A train travels 60 km in 1 hour. How far in 3 hours?','',['120 km','180 km','200 km','240 km'],1],['What is 15% of 200?','',['15','20','30','35'],2],['If 8 tickets cost R240, one costs:','',['R20','R25','R30','R40'],2],['A shift starts at 06:45 and lasts 8 hours. Finish time?','',['13:45','14:45','15:45','16:45'],1]]},
{id:'memory',name:'Memory & Recall',icon:'◫',time:5,qs:[
['Remember: 4 — 8 — 2 — 9. What was the second number?','',['2','4','8','9'],2],['Remember: BLUE, 17, EAST. Which direction appeared?','',['North','South','East','West'],2],['Remember: 6, 1, 9, 3, 7. What was last?','',['3','6','7','9'],2],['Remember the code: K7M2. Which code matches?','',['K7N2','K7M2','K2M7','M7K2'],1]]},
{id:'spatial',name:'Spatial & Mechanical',icon:'◈',time:5,qs:[
['If you turn ↑ 90° clockwise, which way?','',['←','→','↓','↑'],1],['Which shape has no corners?','',['Square','Triangle','Circle','Rectangle'],2],['A wheel rotates clockwise. At its top, its movement is toward:','',['Left','Right','Up','Down'],1],['Which is a mirror image of →?','',['→','←','↑','↓'],1]]},
{id:'reaction',name:'Reaction & Response',icon:'↯',time:3,qs:[
['When you see GREEN, choose GO.','GREEN',['GO','STOP','WAIT','NONE'],0],['When you see RED, choose STOP.','RED',['GO','STOP','WAIT','NONE'],1],['When you see AMBER, choose WAIT.','AMBER',['GO','STOP','WAIT','NONE'],2],['When you see GREEN, choose GO.','GREEN',['STOP','WAIT','GO','NONE'],2]]},
{id:'workstyle',name:'Work-Style Practice',icon:'✓',time:5,qs:[
['I follow safety procedures even when under time pressure.','',['Strongly agree','Agree','Disagree','Strongly disagree'],0],['When instructions are unclear, I ask for clarification.','',['Strongly agree','Agree','Disagree','Strongly disagree'],0],['I stay focused when repetitive tasks must be done accurately.','',['Strongly agree','Agree','Disagree','Strongly disagree'],0],['I report a safety concern rather than ignore it.','',['Strongly agree','Agree','Disagree','Strongly disagree'],0]]}
];
let state={module:null,qi:0,score:0,answers:[],timer:null,seconds:0,results:[]};
const $=id=>document.getElementById(id);
function showScreen(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');window.scrollTo(0,0);if(id!=='test') $('timerPill').classList.add('hidden')}
function renderModules(){$('moduleGrid').innerHTML=modules.map((m,i)=>`<article class="module" onclick="startModule(${i})"><span class="num">0${i+1}</span><div style="font-size:28px;color:var(--accent);margin-top:10px">${m.icon}</div><h3>${m.name}</h3><p>${m.qs.length} questions • ${m.time} min</p></article>`).join('')}
function startModule(i){state.module=modules[i];state.qi=0;state.score=0;state.answers=[];state.results=[];startTimer(state.module.time*60);showScreen('test');renderQuestion()}
function startFullMock(){state.module={id:'full',name:'Full Train Assistant Mock',time:30,qs:modules.flatMap(m=>m.qs.map(q=>q))};state.qi=0;state.score=0;state.answers=[];state.results=[];startTimer(30*60);showScreen('test');renderQuestion()}
function startTimer(sec){clearInterval(state.timer);state.seconds=sec;updateTimer();state.timer=setInterval(()=>{state.seconds--;updateTimer();if(state.seconds<=0){clearInterval(state.timer);finishTest()}},1000)}
function updateTimer(){let m=Math.floor(state.seconds/60),s=state.seconds%60;$('timerPill').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;$('timerPill').classList.remove('hidden')}
function renderQuestion(){const q=state.module.qs[state.qi];$('moduleLabel').textContent=state.module.name;$('questionCount').textContent=`Question ${state.qi+1} of ${state.module.qs.length}`;$('progressBar').style.width=`${(state.qi/state.module.qs.length)*100}%`;$('questionMeta').textContent='Choose the answer that best fits the question.';$('questionText').textContent=q[0];$('questionVisual').innerHTML=q[1]?`<div class="sequence">${q[1]}</div>`:'';$('feedback').textContent='';$('nextBtn').disabled=true;$('nextBtn').textContent=state.qi===state.module.qs.length-1?'Finish →':'Continue →';$('answers').innerHTML=q[2].map((a,i)=>`<button class="answer" onclick="choose(${i})">${String.fromCharCode(65+i)}. ${a}</button>`).join('')}
function choose(i){if(state.answers[state.qi]!==undefined)return;const q=state.module.qs[state.qi];state.answers[state.qi]=i;document.querySelectorAll('.answer').forEach((b,n)=>{if(n===i)b.classList.add('selected');if(n===q[3])b.classList.add('correct');if(n===i&&i!==q[3])b.classList.add('wrong')});if(i===q[3])state.score++;$('feedback').textContent=i===q[3]?'✓ Correct':'✕ Review the correct answer highlighted above';$('nextBtn').disabled=false}
function nextQuestion(){if(state.qi<state.module.qs.length-1){state.qi++;renderQuestion()}else finishTest()}
function finishTest(){clearInterval(state.timer);state.results.push({name:state.module.name,score:state.score,total:state.module.qs.length});const pct=Math.round(state.score/state.module.qs.length*100);$('scorePct').textContent=pct+'%';$('resultTitle').textContent=pct>=80?'Strong practice session':pct>=60?'Good foundation':'Keep practising';$('resultSummary').textContent=`You answered ${state.score} of ${state.module.qs.length} questions correctly. Use the module breakdown to target the skills you want to improve.`;$('resultBreakdown').innerHTML=state.results.map(r=>`<div class="break"><b>${Math.round(r.score/r.total*100)}%</b><span>${r.name}</span><small>${r.score}/${r.total} correct</small></div>`).join('');showScreen('results')}
function quitTest(){clearInterval(state.timer);showScreen('modules')}
$('themeBtn').onclick=()=>document.body.classList.toggle('light');
renderModules();